config/routes.rb
Rails.application.routes.draw do
  root 'vacancies#index'
  resources :vacancies, :employees, :skills
  get 'skills/find_id'
  get 'skills/add'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_and_belongs_to_many :skills

  validates :name, :contact, :search, :salary, presence: true

end

app/models/skill.rb
class Skill < ApplicationRecord
  has_and_belongs_to_many :vacancies
  has_and_belongs_to_many :employees

  validates :name, presence: true

  def self.add_skills_from_new(vacancy_or_employee, all_params)
    skills = all_params.to_h[:skills][2..-1].split(', ')
    skills.each do |str|
      i = str.rindex('=')
      name = str[0...i]
      id = str[i+1..-1].to_i
      add_skill(vacancy_or_employee, name, id)
    end
  end

  def self.add_skills_from_edit(vacancy_or_employee, str)
    skills = []
    str.strip.split(/[,\/]/).each do |st|
      name = st.strip.capitalize
      skill = Skill.find_by(name: name)
      skill = Skill.create(name: name) unless skill
      vacancy_or_employee.skills << skill
      skills << skill
    end
    skills
  end

  private

  def self.add_skill(vacancy_or_employee, name, id)
    if id == 0
      vacancy_or_employee.skills << Skill.create(name: name)
    else
      vacancy_or_employee.skills << Skill.find(id)
    end
  end
end

app/models/vacancy.rb
class Vacancy < ApplicationRecord
  has_and_belongs_to_many :skills

  validates :title, :date, :validity, :salary, :contacts, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  def index
    @employees = Employee.all.order(created_at: :desc).page(params[:page])
      .per(params[:per])
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def new
    @employee = Employee.new
    @skills = Skill.all
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      Skill.add_skills_from_new(@employee, all_params)
      redirect_to employees_path, notice: 'Работник создан'
    else
      render 'new'
    end
  end

  def edit
    @employee = Employee.find(params[:id])
    @skill = Skill.new
    @skills = @employee.skills
  end

  def update
    @employee = Employee.find(params[:id])
    if @employee.update(employee_params)
      redirect_to @employee, notice: 'Работник обновлён'
    else
      render 'edit'
    end
  end

  def destroy
  end

  private

  def all_params
    params.require(:vacancy).permit(:name, :contact, :search, :salary, :skills)
  end

  def employee_params
    hash = all_params.to_h
    hash.delete(:skills)
    hash
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def add
    @vacancy = Vacancy.find(params[:vacancy_id])
    @skills = Skill.add_skills_from_edit(@vacancy, name)
    respond_to :js
  end

  def find_id
    skill = Skill.find_by(name: name)
    id = skill ? skill.id : 0
    render json: { 'id': id }
  end

  private

  def name
    params.require(:skill).permit(:name).to_h[:name]
  end
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController

  def index
    @vacancies = Vacancy.all.order(created_at: :desc).page(params[:page])
      .per(params[:per])
  end

  def show
    @vacancy = Vacancy.find(params[:id])
  end

  def new
    @vacancy = Vacancy.new
    @skills = Skill.all
  end

  def create
    @vacancy = Vacancy.new(vacancy_params)
    @vacancy.date = Time.now
    if @vacancy.save
      Skill.add_skills_from_new(@vacancy, all_params)
      redirect_to vacancies_path, notice: 'Вакансия создана'
    else
      render 'new'
    end
  end

  def edit
    @vacancy = Vacancy.find(params[:id])
    @skill = Skill.new
    @skills = @vacancy.skills
  end

  def update
    @vacancy = Vacancy.find(params[:id])
    @vacancy.date = Time.now
    if @vacancy.update(vacancy_params)
      redirect_to @vacancy, notice: 'Вакансия обновлена'
    else
      render 'edit'
    end
  end

  def destroy
  end

  private

  def all_params
    params.require(:vacancy).permit(:title, :salary, :contacts, :validity,
      :skills)
  end

  def vacancy_params
    hash = all_params.to_h
    hash.delete(:skills)
    hash
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/vacancies_helper.rb
module VacanciesHelper
end

app/views/employees/_form.html.haml
%h2.text-center
  = title
%br
%span.col-md-4.col-md-offset-4#inputform
  = form_for @employee do |f|
    .form-group
      = f.label :name, 'ФИО'
      %span#alert-name-empty.hidden
        = render 'shared/alert', message: 'Укажите ФИО'
      %span#alert-name-invalid.hidden
        = render 'shared/alert', message: 'ФИО должно содержать 3 слова и только кириллические буквы и пробелы'
      = f.text_field :name, class: 'form-control', dataindex: '1'

    = render 'shared/skills', btnid: btnid, skills_list: skills_list

    = f.hidden_field :skills, id: 'skills', value: ''
    .form-group
      = f.label :salary, 'Желаемая зарплата'
      %span#alert-salary-empty.hidden
        = render 'shared/alert', message: 'Укажите желаемую зарплату'
      %span#alert-salary-invalid.hidden
        = render 'shared/alert', message: 'Зарплата должна быть целым, положительным числом'
      = f.number_field :salary, class: 'form-control', dataindex: '3'
    .form-group
      = f.label :contact, 'Номер телефона или адрес эл.почты'
      %span#alert-contact-empty.hidden
        = render 'shared/alert', message: 'Укажите номер телефона или адрес эл.почты'
      %span#alert-contact-invalid.hidden
        = render 'shared/alert', message: 'Проверьте номер телефона или адрес эл.почты. Необходимо указать что-то одно: либо номер телефона, либо адрес эл.почты'
      = f.text_field :contact, class: 'form-control', dataindex: '4'
    .checkbox
      = f.check_box :search, dataindex: '5'
      = f.label :search, 'В поиске работы'
    %br
    = f.submit submit_text, class: 'btn btn-success',
      id: 'submit-employee', onsubmit: 'return validate_employee()'

app/views/employees/create.html.erb
<h1>Employees#create</h1>
<p>Find me in app/views/employees/create.html.erb</p>

app/views/employees/destroy.html.erb
<h1>Employees#destroy</h1>
<p>Find me in app/views/employees/destroy.html.erb</p>

app/views/employees/edit.html.erb
<h1>Employees#edit</h1>
<p>Find me in app/views/employees/edit.html.erb</p>

app/views/employees/index.html.haml
%h2.text-center Работники
%br

app/views/employees/new.html.haml
= render 'vacancies/form', title: 'Создание работника',
  submit_text: 'Создать работника', method: :post, btnid: 'add-skill',
  skills_list: 'shared/skills_list_new'

app/views/employees/show.html.erb
<h1>Employees#show</h1>
<p>Find me in app/views/employees/show.html.erb</p>

app/views/employees/update.html.erb
<h1>Employees#update</h1>
<p>Find me in app/views/employees/update.html.erb</p>

app/views/layouts/_top_navigation.html.haml
%nav.navbar
  .container
    .navbar-header
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav
        %li.active
          = link_to 'Вакансии', vacancies_path
        %li
          = link_to 'Работники', employees_path
      %ul.nav.navbar-nav.navbar-right
        %li.active
          = link_to 'Создать вакансию', new_vacancy_path
        %li
          = link_to 'Создать работника', new_employee_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title RecruitmentAgency
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/top_navigation'
    - if flash[:notice]
      .alert.alert-info.text-center
        = flash[:notice]
    = yield

app/views/shared/_alert.html.haml
.alert.alert-danger{ role: 'alert' }
  %span.glyphicon.glyphicon-exclamation-sign{ 'aria-hidden' => 'true' }
  %span.sr-only Error:
  = message

app/views/shared/_skill_button.html.haml
= button_tag skillname, type: 'button', id: skillname, vacancyid: @vacancy.id,
  skillid: skillid, class: 'btn btn-primary glyphicon glyphicon-remove-right'

app/views/shared/_skills.html.haml
.form-group.form-inline
  = label_tag 'skill', 'Умение'
  %span#alert-few-skills.hidden
    = render 'shared/alert', message: 'Укажите несколько требуемых умений'
  = text_field_tag 'skill', nil, class: 'form-control', id: 'skill',
    list: 'skill-name', dataindex: '2'
  %datalist#skill-name
    - Skill.all.each do |skill|
      %option{ value: "#{skill.name}" }
  = button_tag 'Добавить', type: 'button', class: 'btn btn-info', id: btnid
  -#= link_to 'Добавить!!!!!!',
  -#  skills_path,
  -#  method: :post, class: 'btn btn-info', remote: true
  %span#some-form
  %br
  %span#skills-list
    = render skills_list

app/views/shared/_skills_list_edit.html.haml
- @skills.each do |skill|
  = render 'shared/skill_button', skillname: skill.name, skillid: skill.id

app/views/shared/_skills_list_new.html.haml
= button_tag 'Sample', type: 'button', id: 'sample', skillid: '0',
  class: 'btn btn-primary glyphicon glyphicon-remove-right hidden'

app/views/skills/_add.js.erb
console.log('js!!!!!!!!!!!');
//$('#some-form').html("%= j (render 'vacancies/some_form')%>");



<% @skills.each do |skill| %>
  $('#skills-list').html("<%= j (render 'shared/skill_button', skillname: skill.name, skillid: skill.id) %>");
<% end %>

app/views/skills/create.html.erb
<h1>Skills#create</h1>
<p>Find me in app/views/skills/create.html.erb</p>

app/views/skills/destroy.html.erb
<h1>Skills#destroy</h1>
<p>Find me in app/views/skills/destroy.html.erb</p>

app/views/skills/edit.html.erb
<h1>Skills#edit</h1>
<p>Find me in app/views/skills/edit.html.erb</p>

app/views/skills/index.html.erb
<h1>Skills#index</h1>
<p>Find me in app/views/skills/index.html.erb</p>

app/views/skills/new.html.erb
<h1>Skills#new</h1>
<p>Find me in app/views/skills/new.html.erb</p>

app/views/skills/update.html.erb
<h1>Skills#update</h1>
<p>Find me in app/views/skills/update.html.erb</p>

app/views/vacancies/_form.html.haml
%h2.text-center
  = title
%br
%span.col-md-4.col-md-offset-4#inputform
  = form_for @vacancy, method: method, html: { name: 'vacancy' } do |f|
    .form-group
      = f.label :title, 'Название'
      %span#alert-title-empty.hidden
        = render 'shared/alert', message: 'Введите название вакансии'
      = f.text_field :title, class: 'form-control', dataindex: '1'

    = render 'shared/skills', btnid: btnid, skills_list: skills_list

    = f.hidden_field :skills, id: 'skills', value: ''
    .form-group
      = f.label :salary, 'Зарплата'
      %span#alert-salary-empty.hidden
        = render 'shared/alert', message: 'Укажите зарплату'
      %span#alert-salary-invalid.hidden
        = render 'shared/alert',
          message: 'Зарплата должна быть целым, положительным числом'
      = f.number_field :salary, class: 'form-control', dataindex: '3'
    .form-group
      = f.label :contacts, 'Контактная информация'
      %span#alert-contacts-empty.hidden
        = render 'shared/alert', message: 'Укажите контактную информацию'
      = f.text_area :contacts, class: 'form-control', dataindex: '4'
    .form-group
      = f.label :validity, 'Срок действия, дней'
      %span#alert-validity-empty.hidden
        = render 'shared/alert', message: 'Укажите срок действия'
      %span#alert-validity-invalid.hidden
        = render 'shared/alert',
          message: 'Срок действия должен быть целым, положительным числом'
      = f.number_field :validity, class: 'form-control', dataindex: '5'
    %br
    = f.submit submit_text, class: 'btn btn-success',
      id: 'submit-vacancy', onsubmit: 'return validate_vacancy()'

app/views/vacancies/_index.js.erb
$('#vacancies').html("<%= j (render 'vacancies/vacancies') %>");
$('#paginator').html("<%= j (paginate(@vacancies, remote: true)) %>");

app/views/vacancies/_some_form.html.erb
AAAAAAAAAAAAAAAAAAAAAAA!!!!!!!!!!!!!!!!!!!!!!!!!!!

app/views/vacancies/_vacancies.html.haml
.row
  - @vacancies.each do |vacancy|
    .col-md-4
      %h2
        = link_to vacancy.title, vacancy_path(vacancy)
      %h5
        %em
          .row
            .text-left.col-md-6
              = vacancy.date
              %small
                опубликована.
            .text-right.col-md-6
              %small
                Размещена до
              = vacancy.date + vacancy.validity
      %h4.text-right
        %em
          %small
            Зарплата
          = vacancy.salary
      Умения:
      %h4
        %ul
          %li
            = vacancy.skills[0].name
          %li
            = "#{vacancy.skills[1].name} ..."

app/views/vacancies/create.html.erb
<h1>Vacancies#create</h1>
<p>Find me in app/views/vacancies/create.html.erb</p>

app/views/vacancies/delete___edit.html.erb
<%= link_to 'Добавить!!!!!!', skills_path, method: :post, class: 'btn btn-info', remote: true %>
<span id="some-form"></span>

app/views/vacancies/delete_index.js.coffee.haml
$('#vacancies').html("#{escape_javascript(render 'vacancies/vacancies')}")
$('#paginator').html("#{escape_javascript(paginate(@vacancies, remote: true))}")

app/views/vacancies/destroy.html.erb
<h1>Vacancies#destroy</h1>
<p>Find me in app/views/vacancies/destroy.html.erb</p>

app/views/vacancies/edit.html.haml
= hidden_field_tag 'vacancy_id', @vacancy.id
= render 'vacancies/form', title: 'Редактирование вакансии',
  submit_text: 'Сохранить вакансию', method: :patch, btnid: 'add-skill-edit',
  skills_list: 'shared/skills_list_edit'

app/views/vacancies/index.html.haml
%h1.text-center Вакансии
%br
.row
  .col-md-8.col-md-offset-2
    #vacancies
      = render 'vacancies/vacancies'
    %br
    %br
    #paginator.text-center
      = paginate @vacancies, remote: true,
       theme: 'twitter-bootstrap-3', pagination_class: 'pagination-md'

app/views/vacancies/new.html.haml
= render 'vacancies/form', title: 'Создание вакансии',
  submit_text: 'Создать вакансию', method: :post, btnid: 'add-skill-new',
  skills_list: 'shared/skills_list_new'

app/views/vacancies/show.html.haml
.col-md-4.col-md-offset-4
  %h2.text-center
    = @vacancy.title
    %h5
      %em
        .row
          .text-left.col-md-6
            = @vacancy.date
            %small
              опубликована.
          .text-right.col-md-6
            %small
              Размещена до
            = @vacancy.date + @vacancy.validity
    %h4.text-right
      %em
        %small
          Зарплата
        = @vacancy.salary
    Умения:
    %h4
      %ul
        - @vacancy.skills.each do |skill|
          %li
            = skill.name

    %span
      Контакты:
      = @vacancy.contacts

  = link_to 'Редактировать', edit_vacancy_path(@vacancy)

app/views/vacancies/update.html.erb
<h1>Vacancies#update</h1>
<p>Find me in app/views/vacancies/update.html.erb</p>